name: Handle PRs

on:
  pull_request:
    types:
      - opened

jobs:
  run_always:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Step
        run: echo "This step will always run when a new PR is opened"
